CREATE TABLE IF NOT EXISTS active_snapshot_state (
    id VARCHAR(100) PRIMARY KEY,
    active_snapshot_id VARCHAR(255) NULL,
    snapshot_id VARCHAR(255) NULL,
    snapshot_name VARCHAR(255) NULL,
    faiss_index_id VARCHAR(255) NULL,
    source_id VARCHAR(100) NULL,
    dataset_id VARCHAR(150) NULL,
    index_file VARCHAR(1000) NULL,
    metadata_file VARCHAR(1000) NULL,
    embedding_provider VARCHAR(50) NULL DEFAULT 'ollama',
    vector_count INT NOT NULL DEFAULT 0,
    document_count INT NOT NULL DEFAULT 0,
    chunk_count INT NOT NULL DEFAULT 0,
    tag_keyword_build_id VARCHAR(255) NULL,
    graph_build_id VARCHAR(255) NULL,
    ontology_id VARCHAR(255) NULL,
    wiki_build_id VARCHAR(255) NULL,
    activated_at VARCHAR(40) NULL,
    activated_by VARCHAR(100) NULL,
    previous_snapshot_id VARCHAR(255) NULL,
    rollback_available BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT NULL,
    created_at VARCHAR(40) NULL,
    updated_at VARCHAR(40) NULL,
    KEY idx_active_snapshot_state_snapshot (active_snapshot_id),
    KEY idx_active_snapshot_state_source (source_id),
    KEY idx_active_snapshot_state_dataset (dataset_id)
);
